name: Format and Fix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push changes back to the repo
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} # Check out the head of the PR branch

      - name: Run clang-format and apply fixes
        uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: '.'
          extensions: 'h,cpp,c,hpp, tpp'
          clangFormatVersion: 16
          style: file
          inplace: True # This modifies the files in the runner workspace

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-fix formatting with clang-format"
          file_pattern: '*' # Only commits changed files
